[monitor:///opt/splunk/ctf_logs/]
index = ctf
sourcetype = auto

[source::.../dns_queries.log]
sourcetype = dns

[source::.../web_access.log]
sourcetype = access_combined

[source::.../auth.log]
sourcetype = linux_secure

[source::.../syslog.log]
sourcetype = syslog
